<?php


namespace App\Services\News;

use App\Models\News\NewsCategory;
use App\Repositories\Contracts\NewsCategoryRepositoryInterface;
use App\Exceptions\Api\NotFoundException;
use App\Exceptions\Api\ValidationException;
use Illuminate\Database\Eloquent\Collection;

class NewsCategoryService
{
    public function __construct(
        private NewsCategoryRepositoryInterface $newsCategoryRepository
    ) {}

    /**
     * Get all categories
     */
    public function getAllCategories(): Collection
    {
        return $this->newsCategoryRepository->getCategoriesWithPostsCount();
    }

    /**
     * Get categories with published posts (for public)
     */
    public function getCategoriesWithPublishedPosts(): Collection
    {
        return $this->newsCategoryRepository->getCategoriesWithPublishedPosts();
    }

    /**
     * Get popular categories
     */
    public function getPopularCategories(int $limit = 10): Collection
    {
        return $this->newsCategoryRepository->getPopularCategories($limit);
    }

    /**
     * Get category by ID
     */
    public function getCategoryById(string $id): NewsCategory
    {
        $category = $this->newsCategoryRepository->find($id, ['*'], ['posts']);

        if (!$category) {
            throw new NotFoundException('News category not found');
        }

        return $category;
    }

    /**
     * Get category by slug
     */
    public function getCategoryBySlug(string $slug): NewsCategory
    {
        $category = $this->newsCategoryRepository->findBySlug($slug);

        if (!$category) {
            throw new NotFoundException('News category not found');
        }

        return $category;
    }

    /**
     * Create category
     */
    public function createCategory(array $data): NewsCategory
    {
        // Check if category name exists
        $existing = $this->newsCategoryRepository->findBy('name', $data['name']);
        if ($existing) {
            throw new ValidationException('Category name already exists');
        }

        // Slug will be auto-generated by HasSlug trait

        return $this->newsCategoryRepository->create($data);
    }

    /**
     * Update category
     */
    public function updateCategory(string $id, array $data): NewsCategory
    {
        $category = $this->getCategoryById($id);

        // Check if new name exists (excluding current category)
        if (isset($data['name']) && $data['name'] !== $category->name) {
            $existing = $this->newsCategoryRepository->findBy('name', $data['name']);
            if ($existing) {
                throw new ValidationException('Category name already exists');
            }
        }

        $this->newsCategoryRepository->update($id, $data);

        return $category->fresh();
    }

    /**
     * Delete category
     */
    public function deleteCategory(string $id): bool
    {
        $category = $this->getCategoryById($id);

        // Check if category has posts
        if ($category->posts()->count() > 0) {
            throw new ValidationException(
                'Cannot delete category with existing posts. Please remove or reassign posts first.'
            );
        }

        return $this->newsCategoryRepository->delete($id);
    }
}